### ISSUE TITLE
needs requirements.txt

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/PortfolioChoiceBlogPost#1]

**Comment by sbenthall** [comment]
fixed with https://github.com/econ-ark/PortfolioChoiceBlogPost/commit/9d0606fef92d3a8569f29a4193256de2d68f1c93

**Comment by Mv77** [comment]
I'm clicking the [Binder link from econ-ark.org](https://mybinder.org/v2/gh/econ-ark/PortfolioChoiceBlogPost/master?filepath=PortfolioChoiceBlogPost.html) and it is broken.

The issue seems to be related to `requirements.txt`. The error message I'm getting is

`Could not find a version that satisfies the requirement pkg-resources==0.0.0`
